/* Generated By:JJTree: Do not edit this line. ASTAccessExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAccessExpression extends SimpleNode {
  public ASTAccessExpression(int id) {
    super(id);
  }

  public ASTAccessExpression(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d8aead7a62045063534d179336080f3a (do not edit this line) */
