/* Generated By:JJTree: Do not edit this line. ASTAlgo.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAlgo extends SimpleNode {
  public ASTAlgo(int id) {
    super(id);
  }

  public ASTAlgo(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1d30e8d95fd84d31e642cd679a3051b5 (do not edit this line) */
