/* Generated By:JJTree: Do not edit this line. ASTAssing.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssing extends SimpleNode {
  public ASTAssing(int id) {
    super(id);
  }

  public ASTAssing(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=db084e2929f86b8481b7b0abb0deca47 (do not edit this line) */
