/* Generated By:JJTree: Do not edit this line. ASTAdditive.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAdditive extends SimpleNode {
  private String name;

  public ASTAdditive(int id) {
    super(id);
  }

  public ASTAdditive(Jmm p, int id) {
    super(p, id);
  }

  /**
  * Set the name.
  * @param n the name
  */
  public void setName(String n) {
    name = n;
  }

  /**
   * {@inheritDoc}
   * @see org.javacc.examples.jjtree.eg2.SimpleNode#toString()
   */
  public String toString() {
    return JmmTreeConstants.jjtNodeName[id] + " '" + name + "' ";
  }

}
/* JavaCC - OriginalChecksum=10c77feb03e23ccd2a6c49c48e5b6d58 (do not edit this line) */
