/* Generated By:JJTree: Do not edit this line. ASTAndL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAndL extends SimpleNode {
  public ASTAndL(int id) {
    super(id);
  }

  public ASTAndL(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fb6dddb505b13554e747f191c20fbc1b (do not edit this line) */
