/* Generated By:JJTree: Do not edit this line. ASTBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBody extends SimpleNode {
  public ASTBody(int id) {
    super(id);
  }

  public ASTBody(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d8d4a56ba692cd9d06d14abd19cb975e (do not edit this line) */
