/* Generated By:JJTree: Do not edit this line. ASTEXT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEXT extends SimpleNode {
  public ASTEXT(int id) {
    super(id);
  }

  public ASTEXT(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c9701e2eac73dfec82432be66b90927d (do not edit this line) */
