/* Generated By:JJTree: Do not edit this line. ASTExtend.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExtend extends SimpleNode {
  public ASTExtend(int id) {
    super(id);
  }

  public ASTExtend(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8caeb7c938e482b29a611e986a15698d (do not edit this line) */
