/* Generated By:JJTree: Do not edit this line. ASTID.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTID extends SimpleNode {
  public ASTID(int id) {
    super(id);
  }

  public ASTID(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ef01e00d08c743fc805e1b5fa6f3b399 (do not edit this line) */
