/* Generated By:JJTree: Do not edit this line. ASTLessThan.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLessThan extends SimpleNode {
  public ASTLessThan(int id) {
    super(id);
  }

  public ASTLessThan(Jmm p, int id) {
    super(p, id);
  }

  
  /**
  * {@inheritDoc}
  * @see org.javacc.examples.jjtree.eg2.SimpleNode#toString()
  */
  public String toString() {
    return JmmTreeConstants.jjtNodeName[id] + " '<' ";
  }

}
/* JavaCC - OriginalChecksum=9ba8f240fcb8826afc35454c886f9934 (do not edit this line) */
