/* Generated By:JJTree: Do not edit this line. ASTMultiplicative.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMultiplicative extends SimpleNode {
  public ASTMultiplicative(int id) {
    super(id);
  }

  public ASTMultiplicative(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=79101242f2399ecfc89dd939c468aa11 (do not edit this line) */
