/* Generated By:JJTree: Do not edit this line. ASTNew.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNew extends SimpleNode {
  public ASTNew(int id) {
    super(id);
  }

  public ASTNew(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4b6a9edd0aab1ee154d17080ccd71312 (do not edit this line) */
