/* Generated By:JJTree: Do not edit this line. ASTParams.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParams extends SimpleNode {
  public ASTParams(int id) {
    super(id);
  }

  public ASTParams(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=211b74f6b2846055a1be3fe84b090578 (do not edit this line) */
