/* Generated By:JJTree: Do not edit this line. ASTStatementAux.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatementAux extends SimpleNode {
  public ASTStatementAux(int id) {
    super(id);
  }

  public ASTStatementAux(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=50ed0433aa9b24fc3392f3d30749c799 (do not edit this line) */
