/* Generated By:JJTree: Do not edit this line. ASTvoid.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvoid extends SimpleNode {
  public ASTvoid(int id) {
    super(id);
  }

  public ASTvoid(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=27d37fc01d49b162f7dd83254f564403 (do not edit this line) */
