/* Generated By:JJTree&JavaCC: Do not edit this line. JmmConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JmmConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 4;
  /** RegularExpression Id. */
  int ADDSUB_OP = 5;
  /** RegularExpression Id. */
  int ARITH_OP = 6;
  /** RegularExpression Id. */
  int AND = 7;
  /** RegularExpression Id. */
  int BRACKET_R = 8;
  /** RegularExpression Id. */
  int BRACKET_L = 9;
  /** RegularExpression Id. */
  int BOOL = 10;
  /** RegularExpression Id. */
  int BOOLEAN = 11;
  /** RegularExpression Id. */
  int CLASS = 12;
  /** RegularExpression Id. */
  int CHAV_R = 13;
  /** RegularExpression Id. */
  int CHAV_L = 14;
  /** RegularExpression Id. */
  int EQ = 15;
  /** RegularExpression Id. */
  int EXT = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int INT = 19;
  /** RegularExpression Id. */
  int LF = 20;
  /** RegularExpression Id. */
  int LENGTH = 21;
  /** RegularExpression Id. */
  int MAIN = 22;
  /** RegularExpression Id. */
  int NEW = 23;
  /** RegularExpression Id. */
  int NOT = 24;
  /** RegularExpression Id. */
  int PAR_R = 25;
  /** RegularExpression Id. */
  int PAR_L = 26;
  /** RegularExpression Id. */
  int PFINAL = 27;
  /** RegularExpression Id. */
  int PUBLIC = 28;
  /** RegularExpression Id. */
  int RET = 29;
  /** RegularExpression Id. */
  int LESSTHAN = 30;
  /** RegularExpression Id. */
  int SCOLON = 31;
  /** RegularExpression Id. */
  int STATIC = 32;
  /** RegularExpression Id. */
  int STR = 33;
  /** RegularExpression Id. */
  int THIS = 34;
  /** RegularExpression Id. */
  int VIRG = 35;
  /** RegularExpression Id. */
  int VOID = 36;
  /** RegularExpression Id. */
  int WHILE = 37;
  /** RegularExpression Id. */
  int IDENTIFIER = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<INTEGER>",
    "<ADDSUB_OP>",
    "<ARITH_OP>",
    "\"&&\"",
    "\"]\"",
    "\"[\"",
    "<BOOL>",
    "\"boolean\"",
    "\"class\"",
    "\"}\"",
    "\"{\"",
    "\"=\"",
    "\"extends\"",
    "\"else\"",
    "\"if\"",
    "\"int\"",
    "\"\\n\"",
    "\"length\"",
    "\"main\"",
    "\"new\"",
    "\"!\"",
    "\")\"",
    "\"(\"",
    "\".\"",
    "\"public\"",
    "\"return\"",
    "\"<\"",
    "\";\"",
    "\"static\"",
    "\"String\"",
    "\"this\"",
    "\",\"",
    "\"void\"",
    "\"while\"",
    "<IDENTIFIER>",
  };

}
