/* Generated By:JJTree&JavaCC: Do not edit this line. JmmConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JmmConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 6;
  /** RegularExpression Id. */
  int ADDSUB_OP = 7;
  /** RegularExpression Id. */
  int ARITH_OP = 8;
  /** RegularExpression Id. */
  int AND = 9;
  /** RegularExpression Id. */
  int BRACKET_R = 10;
  /** RegularExpression Id. */
  int BRACKET_L = 11;
  /** RegularExpression Id. */
  int BOOL = 12;
  /** RegularExpression Id. */
  int BOOLEAN = 13;
  /** RegularExpression Id. */
  int CLASS = 14;
  /** RegularExpression Id. */
  int CHAV_R = 15;
  /** RegularExpression Id. */
  int CHAV_L = 16;
  /** RegularExpression Id. */
  int EQ = 17;
  /** RegularExpression Id. */
  int EXT = 18;
  /** RegularExpression Id. */
  int ELSE = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int INT = 21;
  /** RegularExpression Id. */
  int LF = 22;
  /** RegularExpression Id. */
  int LENGTH = 23;
  /** RegularExpression Id. */
  int MAIN = 24;
  /** RegularExpression Id. */
  int NEW = 25;
  /** RegularExpression Id. */
  int NOT = 26;
  /** RegularExpression Id. */
  int PAR_R = 27;
  /** RegularExpression Id. */
  int PAR_L = 28;
  /** RegularExpression Id. */
  int PFINAL = 29;
  /** RegularExpression Id. */
  int PUBLIC = 30;
  /** RegularExpression Id. */
  int RET = 31;
  /** RegularExpression Id. */
  int LESSTHAN = 32;
  /** RegularExpression Id. */
  int SCOLON = 33;
  /** RegularExpression Id. */
  int STATIC = 34;
  /** RegularExpression Id. */
  int STR = 35;
  /** RegularExpression Id. */
  int THIS = 36;
  /** RegularExpression Id. */
  int VIRG = 37;
  /** RegularExpression Id. */
  int VOID = 38;
  /** RegularExpression Id. */
  int WHILE = 39;
  /** RegularExpression Id. */
  int IDENTIFIER = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<token of kind 4>",
    "<token of kind 5>",
    "<INTEGER>",
    "<ADDSUB_OP>",
    "<ARITH_OP>",
    "\"&&\"",
    "\"]\"",
    "\"[\"",
    "<BOOL>",
    "\"boolean\"",
    "\"class\"",
    "\"}\"",
    "\"{\"",
    "\"=\"",
    "\"extends\"",
    "\"else\"",
    "\"if\"",
    "\"int\"",
    "\"\\n\"",
    "\"length\"",
    "\"main\"",
    "\"new\"",
    "\"!\"",
    "\")\"",
    "\"(\"",
    "\".\"",
    "\"public\"",
    "\"return\"",
    "\"<\"",
    "\";\"",
    "\"static\"",
    "\"String\"",
    "\"this\"",
    "\",\"",
    "\"void\"",
    "\"while\"",
    "<IDENTIFIER>",
  };

}
