/* Generated By:JavaCC: Do not edit this line. JmmTreeConstants.java Version 6.0_1 */
public interface JmmTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTEXTEND = 2;
  public int JJTVOID = 3;
  public int JJTVARDECLARATION = 4;
  public int JJTMAINDECLARATION = 5;
  public int JJTMETHODDECLARATION = 6;
  public int JJTIFELSESTATEMENT = 7;
  public int JJTWHILESTATEMENT = 8;
  public int JJTASSING = 9;
  public int JJTAND = 10;
  public int JJTLESSTHAN = 11;
  public int JJTADDITIVE = 12;
  public int JJTMULTIPLICATIVE = 13;
  public int JJTEXPRESSION = 14;
  public int JJTACCESSEXPR = 15;
  public int JJTID = 16;
  public int JJTINTEGER = 17;
  public int JJTBOOL = 18;


  public String[] jjtNodeName = {
    "Program",
    "ClassDeclaration",
    "Extend",
    "void",
    "VarDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "IfElseStatement",
    "WhileStatement",
    "Assing",
    "AND",
    "LessThan",
    "Additive",
    "Multiplicative",
    "Expression",
    "AccessExpr",
    "ID",
    "Integer",
    "Bool",
  };
}
/* JavaCC - OriginalChecksum=bd7cac547bd59fa793f90165d66547a8 (do not edit this line) */
