/* Generated By:JavaCC: Do not edit this line. JmmTreeConstants.java Version 6.0_1 */
public interface JmmTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTVOID = 2;
  public int JJTVARDECLARATION = 3;
  public int JJTMAINDECLARATION = 4;
  public int JJTMETHODDECLARATION = 5;
  public int JJTTYPE = 6;
  public int JJTSTATEMENT = 7;
  public int JJTEXPRESSION = 8;


  public String[] jjtNodeName = {
    "Program",
    "ClassDeclaration",
    "void",
    "VarDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "Type",
    "Statement",
    "Expression",
  };
}
/* JavaCC - OriginalChecksum=ff040025acc8b3012cca8155cef5a79d (do not edit this line) */
