/* Generated By:JJTree: Do not edit this line. ASTAND.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAND extends SimpleNode {
  public ASTAND(int id) {
    super(id);
  }

  public ASTAND(Jmm p, int id) {
    super(p, id);
  }

  /**
  * {@inheritDoc}
  * @see org.javacc.examples.jjtree.eg2.SimpleNode#toString()
  */
  public String toString() {
    return JmmTreeConstants.jjtNodeName[id] + " '&&' ";
  }


}
/* JavaCC - OriginalChecksum=af34d54a63f7022d2873ec9d0195ce46 (do not edit this line) */
