/* Generated By:JJTree: Do not edit this line. ASTAccessExpr.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAccessExpr extends SimpleNode {
  public ASTAccessExpr(int id) {
    super(id);
  }

  public ASTAccessExpr(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5fa1a70f769c56d7c132900d7c5ce85d (do not edit this line) */
