/* Generated By:JJTree: Do not edit this line. ASTincErrCounter.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTincErrCounter extends SimpleNode {
  public ASTincErrCounter(int id) {
    super(id);
  }

  public ASTincErrCounter(Jmm p, int id) {
    super(p, id);
  }

  /**
  * {@inheritDoc}
  * @see org.javacc.examples.jjtree.eg2.SimpleNode#toString()
  */
  public String toString() {
    return "Error_Parsing";
  }

}
/* JavaCC - OriginalChecksum=bf2fa23372302de071c2217a59c7960f (do not edit this line) */
