/* Generated By:JJTree: Do not edit this line. ASTID.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTID extends SimpleNode {
  private String name;
  private String type = null;

  public ASTID(int id) {
    super(id);
  }

  public ASTID(Jmm p, int id) {
    super(p, id);
  }

  /**
  * Set the name.
  * @param n the name
  */
  public void setName(String n) {
    name = n;
  }

  /**
  * Set the param.
  * @param n the name
  * @param t the type
  */
  public void setParam(String n, String t) {
    name = n;
    type = t;
  }


  /**
   * {@inheritDoc}
   * @see org.javacc.examples.jjtree.eg2.SimpleNode#toString()
   */
  public String toString() {
    if(type != null)
      return JmmTreeConstants.jjtNodeName[id] + " " + type + "(" + name + ")";
    else 
      return JmmTreeConstants.jjtNodeName[id] + " (" + name + ")";
  }

}
/* JavaCC - OriginalChecksum=ef01e00d08c743fc805e1b5fa6f3b399 (do not edit this line) */
