/* Generated By:JJTree: Do not edit this line. ASTInteger.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInteger extends SimpleNode {
  private String name;

  public ASTInteger(int id) {
    super(id);
  }

  public ASTInteger(Jmm p, int id) {
    super(p, id);
  }

  /**
  * Set the name.
  * @param n the name
  */
  public void setName(String n) {
    name = n;
  }

  /**
   * {@inheritDoc}
   * @see org.javacc.examples.jjtree.eg2.SimpleNode#toString()
   */
  public String toString() {
    return JmmTreeConstants.jjtNodeName[id] + " '" + name + "' ";
  }

}
/* JavaCC - OriginalChecksum=41e4a88caea2276d6d4d045c90aed658 (do not edit this line) */
