/* Generated By:JJTree: Do not edit this line. ASTIfElseStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIfElseStatement extends SimpleNode {
  public ASTIfElseStatement(int id) {
    super(id);
  }

  public ASTIfElseStatement(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2b9635a34a58a08e8ffe60ae5050c299 (do not edit this line) */
