/* Generated By:JJTree: Do not edit this line. ASTNewExpr.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNewExpr extends SimpleNode {
  public ASTNewExpr(int id) {
    super(id);
  }

  public ASTNewExpr(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=64ec9aabe6f4d3d1279a7a00a60a8d45 (do not edit this line) */
