/* Generated By:JJTree: Do not edit this line. ASTThis.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTThis extends SimpleNode {
  public ASTThis(int id) {
    super(id);
  }

  public ASTThis(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=88907b99a702a8ffe6a0c4228e4c2a30 (do not edit this line) */
