/* Generated By:JavaCC: Do not edit this line. JmmTreeConstants.java Version 6.0_1 */
public interface JmmTreeConstants
{
  public int JJTERROR_SKIPTO = 0;
  public int JJTINCERRCOUNTER = 1;
  public int JJTPROGRAM = 2;
  public int JJTCLASSDECLARATION = 3;
  public int JJTEXTEND = 4;
  public int JJTVOID = 5;
  public int JJTVARDECLARATION = 6;
  public int JJTMAINDECLARATION = 7;
  public int JJTMETHODDECLARATION = 8;
  public int JJTRET = 9;
  public int JJTRETURN = 10;
  public int JJTBODY = 11;
  public int JJTPARAMS = 12;
  public int JJTIFELSESTATEMENT = 13;
  public int JJTWHILESTATEMENT = 14;
  public int JJTASSING = 15;
  public int JJTAND = 16;
  public int JJTLESSTHAN = 17;
  public int JJTADDITIVE = 18;
  public int JJTMULTIPLICATIVE = 19;
  public int JJTEXPRESSION = 20;
  public int JJTACCESSEXPR = 21;
  public int JJTTHIS = 22;
  public int JJTNEWEXPR = 23;
  public int JJTID = 24;
  public int JJTINTEGER = 25;
  public int JJTBOOL = 26;


  public String[] jjtNodeName = {
    "error_skipto",
    "incErrCounter",
    "Program",
    "ClassDeclaration",
    "Extend",
    "void",
    "VarDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "Ret",
    "Return",
    "Body",
    "Params",
    "IfElseStatement",
    "WhileStatement",
    "Assing",
    "AND",
    "LessThan",
    "Additive",
    "Multiplicative",
    "Expression",
    "AccessExpr",
    "This",
    "NewExpr",
    "ID",
    "Integer",
    "Bool",
  };
}
/* JavaCC - OriginalChecksum=6b579a3d978355bdbd0df100413e8537 (do not edit this line) */
