/* Generated By:JavaCC: Do not edit this line. JmmTreeConstants.java Version 6.0_1 */
public interface JmmTreeConstants
{
  public int JJTERROR_SKIPTO = 0;
  public int JJTPROGRAM = 1;
  public int JJTCLASSDECLARATION = 2;
  public int JJTEXTEND = 3;
  public int JJTVOID = 4;
  public int JJTVARDECLARATION = 5;
  public int JJTMAINDECLARATION = 6;
  public int JJTMETHODDECLARATION = 7;
  public int JJTRET = 8;
  public int JJTRETURN = 9;
  public int JJTBODY = 10;
  public int JJTPARAMS = 11;
  public int JJTIFELSESTATEMENT = 12;
  public int JJTWHILESTATEMENT = 13;
  public int JJTASSING = 14;
  public int JJTAND = 15;
  public int JJTLESSTHAN = 16;
  public int JJTADDITIVE = 17;
  public int JJTMULTIPLICATIVE = 18;
  public int JJTEXPRESSION = 19;
  public int JJTACCESSEXPR = 20;
  public int JJTTHIS = 21;
  public int JJTNEWEXPR = 22;
  public int JJTID = 23;
  public int JJTINTEGER = 24;
  public int JJTBOOL = 25;


  public String[] jjtNodeName = {
    "error_skipto",
    "Program",
    "ClassDeclaration",
    "Extend",
    "void",
    "VarDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "Ret",
    "Return",
    "Body",
    "Params",
    "IfElseStatement",
    "WhileStatement",
    "Assing",
    "AND",
    "LessThan",
    "Additive",
    "Multiplicative",
    "Expression",
    "AccessExpr",
    "This",
    "NewExpr",
    "ID",
    "Integer",
    "Bool",
  };
}
/* JavaCC - OriginalChecksum=32db5139ca60e675a2a559c61a8ea23d (do not edit this line) */
